// This file is auto generated by the gqlToTs.ts module
// tslint:disable
// graphql typescript definitions

declare namespace GQL {
  interface IGraphQLResponseRoot {
    data?: IQuery | IMutation;
    errors?: Array<IGraphQLResponseError>;
  }

  interface IGraphQLResponseError {
    message: string;            // Required for all errors
    locations?: Array<IGraphQLResponseErrorLocation>;
    [propName: string]: any;    // 7.2.2 says 'GraphQL servers may provide additional entries to error'
  }

  interface IGraphQLResponseErrorLocation {
    line: number;
    column: number;
  }

  /*
    description: 
  */
  interface IQuery {
    getPerson: IPersonType | null;
    persons: Array<IPersonType> | null;
    getPersonWithExtra: IExtra | null;
  }

  /*
    description: 
  */
  interface IPersonType {
    name: string | null;
    id: string | null;
    sex: string | null;
  }

  /*
    description: 
  */
  interface IExtra {
    speed: number | null;
    person: IPersonType | null;
    agility: IAgilityMeasure | null;
  }

  /*
    description: 
  */
  interface IAgilityMeasure {
    value: number | null;
  }

  /*
    description: 
  */
  interface IMutation {
    addPerson: IPersonType | null;
  }
}

// tslint:enable
